<?php


 function autoload_72259f70a1bfb87ba4d832e1177092eb($class)
{
    $classes = array(
        'Boskee\ProofHQ\SoapService' => __DIR__ .'/SoapService.php',
        'Boskee\ProofHQ\SOAPLoginObject' => __DIR__ .'/SOAPLoginObject.php',
        'Boskee\ProofHQ\SOAPFileUploadObject' => __DIR__ .'/SOAPFileUploadObject.php',
        'Boskee\ProofHQ\SOAPFileUploadObjectArray' => __DIR__ .'/SOAPFileUploadObjectArray.php',
        'Boskee\ProofHQ\SOAPFileSettingsObject' => __DIR__ .'/SOAPFileSettingsObject.php',
        'Boskee\ProofHQ\StringArray' => __DIR__ .'/StringArray.php',
        'Boskee\ProofHQ\SOAPFileLinkObject' => __DIR__ .'/SOAPFileLinkObject.php',
        'Boskee\ProofHQ\SOAPFileLinkObjectArray' => __DIR__ .'/SOAPFileLinkObjectArray.php',
        'Boskee\ProofHQ\SOAPRecipientDecisionReasonObject' => __DIR__ .'/SOAPRecipientDecisionReasonObject.php',
        'Boskee\ProofHQ\SOAPRecipientDecisionReasonObjectArray' => __DIR__ .'/SOAPRecipientDecisionReasonObjectArray.php',
        'Boskee\ProofHQ\SOAPProgressObject' => __DIR__ .'/SOAPProgressObject.php',
        'Boskee\ProofHQ\SOAPProofStageObject' => __DIR__ .'/SOAPProofStageObject.php',
        'Boskee\ProofHQ\SOAPProofStageObjectArray' => __DIR__ .'/SOAPProofStageObjectArray.php',
        'Boskee\ProofHQ\SOAPFileObject' => __DIR__ .'/SOAPFileObject.php',
        'Boskee\ProofHQ\SOAPRecipientObject' => __DIR__ .'/SOAPRecipientObject.php',
        'Boskee\ProofHQ\SOAPWorkflowProofRecipientRequestUpdateObject' => __DIR__ .'/SOAPWorkflowProofRecipientRequestUpdateObject.php',
        'Boskee\ProofHQ\SOAPWorkflowProofRecipientObject' => __DIR__ .'/SOAPWorkflowProofRecipientObject.php',
        'Boskee\ProofHQ\SOAPFileActivityObject' => __DIR__ .'/SOAPFileActivityObject.php',
        'Boskee\ProofHQ\SOAPFileActivityObjectArray' => __DIR__ .'/SOAPFileActivityObjectArray.php',
        'Boskee\ProofHQ\SOAPProfileObject' => __DIR__ .'/SOAPProfileObject.php',
        'Boskee\ProofHQ\SOAPProfileObjectArray' => __DIR__ .'/SOAPProfileObjectArray.php',
        'Boskee\ProofHQ\SOAPContactProofingDefaultsObject' => __DIR__ .'/SOAPContactProofingDefaultsObject.php',
        'Boskee\ProofHQ\SOAPContactObject' => __DIR__ .'/SOAPContactObject.php',
        'Boskee\ProofHQ\SOAPContactObjectArray' => __DIR__ .'/SOAPContactObjectArray.php',
        'Boskee\ProofHQ\SOAPContactGroupObject' => __DIR__ .'/SOAPContactGroupObject.php',
        'Boskee\ProofHQ\SOAPContactGroupObjectArray' => __DIR__ .'/SOAPContactGroupObjectArray.php',
        'Boskee\ProofHQ\SOAPContactAccountObject' => __DIR__ .'/SOAPContactAccountObject.php',
        'Boskee\ProofHQ\SOAPContactAccountObjectArray' => __DIR__ .'/SOAPContactAccountObjectArray.php',
        'Boskee\ProofHQ\SOAPWorkspaceObject' => __DIR__ .'/SOAPWorkspaceObject.php',
        'Boskee\ProofHQ\SOAPWorkspaceObjectArray' => __DIR__ .'/SOAPWorkspaceObjectArray.php',
        'Boskee\ProofHQ\SOAPFileObjectArray' => __DIR__ .'/SOAPFileObjectArray.php',
        'Boskee\ProofHQ\AnyTypeArray' => __DIR__ .'/AnyTypeArray.php',
        'Boskee\ProofHQ\SOAPFileListViewObject' => __DIR__ .'/SOAPFileListViewObject.php',
        'Boskee\ProofHQ\SOAPFileListViewObjectArray' => __DIR__ .'/SOAPFileListViewObjectArray.php',
        'Boskee\ProofHQ\SOAPFileListViewCollectionObject' => __DIR__ .'/SOAPFileListViewCollectionObject.php',
        'Boskee\ProofHQ\SOAPRecipientObjectArray' => __DIR__ .'/SOAPRecipientObjectArray.php',
        'Boskee\ProofHQ\SOAPCommentAttachmentObject' => __DIR__ .'/SOAPCommentAttachmentObject.php',
        'Boskee\ProofHQ\SOAPCommentAttachmentObjectArray' => __DIR__ .'/SOAPCommentAttachmentObjectArray.php',
        'Boskee\ProofHQ\SOAPCommentReplyObject' => __DIR__ .'/SOAPCommentReplyObject.php',
        'Boskee\ProofHQ\SOAPCommentReplyObjectArray' => __DIR__ .'/SOAPCommentReplyObjectArray.php',
        'Boskee\ProofHQ\SOAPCommentObject' => __DIR__ .'/SOAPCommentObject.php',
        'Boskee\ProofHQ\SOAPCommentObjectArray' => __DIR__ .'/SOAPCommentObjectArray.php',
        'Boskee\ProofHQ\SOAPFileEmbedCodeObject' => __DIR__ .'/SOAPFileEmbedCodeObject.php',
        'Boskee\ProofHQ\SOAPFileEmbedCodeObjectArray' => __DIR__ .'/SOAPFileEmbedCodeObjectArray.php',
        'Boskee\ProofHQ\SOAPImageObject' => __DIR__ .'/SOAPImageObject.php',
        'Boskee\ProofHQ\SOAPPlanObject' => __DIR__ .'/SOAPPlanObject.php',
        'Boskee\ProofHQ\SOAPMembershipObject' => __DIR__ .'/SOAPMembershipObject.php',
        'Boskee\ProofHQ\SOAPPermissionsObject' => __DIR__ .'/SOAPPermissionsObject.php',
        'Boskee\ProofHQ\SOAPUserProofingDefaultsObject' => __DIR__ .'/SOAPUserProofingDefaultsObject.php',
        'Boskee\ProofHQ\SOAPUserEmailObject' => __DIR__ .'/SOAPUserEmailObject.php',
        'Boskee\ProofHQ\SOAPUserEmailObjectArray' => __DIR__ .'/SOAPUserEmailObjectArray.php',
        'Boskee\ProofHQ\SOAPUserObject' => __DIR__ .'/SOAPUserObject.php',
        'Boskee\ProofHQ\SOAPUserObjectArray' => __DIR__ .'/SOAPUserObjectArray.php',
        'Boskee\ProofHQ\SOAPAccountPasswordSettingsObject' => __DIR__ .'/SOAPAccountPasswordSettingsObject.php',
        'Boskee\ProofHQ\SOAPAccountProofingDefaultsObject' => __DIR__ .'/SOAPAccountProofingDefaultsObject.php',
        'Boskee\ProofHQ\SOAPAccountObject' => __DIR__ .'/SOAPAccountObject.php',
        'Boskee\ProofHQ\SOAPSatelliteAccountObject' => __DIR__ .'/SOAPSatelliteAccountObject.php',
        'Boskee\ProofHQ\SOAPCallbackObject' => __DIR__ .'/SOAPCallbackObject.php',
        'Boskee\ProofHQ\SOAPCallbackObjectArray' => __DIR__ .'/SOAPCallbackObjectArray.php',
        'Boskee\ProofHQ\SOAPSatelliteAccountObjectArray' => __DIR__ .'/SOAPSatelliteAccountObjectArray.php',
        'Boskee\ProofHQ\SOAPFileRecipientObject' => __DIR__ .'/SOAPFileRecipientObject.php',
        'Boskee\ProofHQ\SOAPFileRecipientObjectArray' => __DIR__ .'/SOAPFileRecipientObjectArray.php',
        'Boskee\ProofHQ\SOAPWorkflowProofAddRecipientRequestObject' => __DIR__ .'/SOAPWorkflowProofAddRecipientRequestObject.php',
        'Boskee\ProofHQ\SOAPWorkflowProofAddRecipientRequestObjectArray' => __DIR__ .'/SOAPWorkflowProofAddRecipientRequestObjectArray.php',
        'Boskee\ProofHQ\SOAPTag' => __DIR__ .'/SOAPTag.php',
        'Boskee\ProofHQ\SOAPTagArray' => __DIR__ .'/SOAPTagArray.php',
        'Boskee\ProofHQ\IntArray' => __DIR__ .'/IntArray.php',
        'Boskee\ProofHQ\SOAPActionObject' => __DIR__ .'/SOAPActionObject.php',
        'Boskee\ProofHQ\SOAPActionObjectArray' => __DIR__ .'/SOAPActionObjectArray.php',
        'Boskee\ProofHQ\SOAPPlanObjectArray' => __DIR__ .'/SOAPPlanObjectArray.php',
        'Boskee\ProofHQ\SOAPDecisionObject' => __DIR__ .'/SOAPDecisionObject.php',
        'Boskee\ProofHQ\SOAPDecisionObjectArray' => __DIR__ .'/SOAPDecisionObjectArray.php',
        'Boskee\ProofHQ\SOAPDecisionReasonObject' => __DIR__ .'/SOAPDecisionReasonObject.php',
        'Boskee\ProofHQ\SOAPDecisionReasonObjectArray' => __DIR__ .'/SOAPDecisionReasonObjectArray.php',
        'Boskee\ProofHQ\SOAPWorkflowTemplateBasicObject' => __DIR__ .'/SOAPWorkflowTemplateBasicObject.php',
        'Boskee\ProofHQ\SOAPWorkflowTemplateBasicObjectArray' => __DIR__ .'/SOAPWorkflowTemplateBasicObjectArray.php',
        'Boskee\ProofHQ\SOAPWorkflowRecipientObject' => __DIR__ .'/SOAPWorkflowRecipientObject.php',
        'Boskee\ProofHQ\SOAPWorkflowRecipientObjectArray' => __DIR__ .'/SOAPWorkflowRecipientObjectArray.php',
        'Boskee\ProofHQ\SOAPWorkflowStageObject' => __DIR__ .'/SOAPWorkflowStageObject.php',
        'Boskee\ProofHQ\SOAPWorkflowStageObjectArray' => __DIR__ .'/SOAPWorkflowStageObjectArray.php',
        'Boskee\ProofHQ\SOAPWorkflowTemplateObject' => __DIR__ .'/SOAPWorkflowTemplateObject.php',
        'Boskee\ProofHQ\SOAPWorkflowRecipientRequestObject' => __DIR__ .'/SOAPWorkflowRecipientRequestObject.php',
        'Boskee\ProofHQ\SOAPWorkflowRecipientRequestObjectArray' => __DIR__ .'/SOAPWorkflowRecipientRequestObjectArray.php',
        'Boskee\ProofHQ\SOAPWorkflowStageRequestObject' => __DIR__ .'/SOAPWorkflowStageRequestObject.php',
        'Boskee\ProofHQ\SOAPWorkflowStageRequestObjectArray' => __DIR__ .'/SOAPWorkflowStageRequestObjectArray.php',
        'Boskee\ProofHQ\SOAPWorkflowStageRequestUpdateObject' => __DIR__ .'/SOAPWorkflowStageRequestUpdateObject.php',
        'Boskee\ProofHQ\SOAPWorkflowRecipientRequestUpdateObject' => __DIR__ .'/SOAPWorkflowRecipientRequestUpdateObject.php',
        'Boskee\ProofHQ\SOAPWorkflowProofRecipientRequestObject' => __DIR__ .'/SOAPWorkflowProofRecipientRequestObject.php',
        'Boskee\ProofHQ\SOAPWorkflowProofRecipientRequestObjectArray' => __DIR__ .'/SOAPWorkflowProofRecipientRequestObjectArray.php',
        'Boskee\ProofHQ\SOAPWorkflowProofStageRequestObject' => __DIR__ .'/SOAPWorkflowProofStageRequestObject.php',
        'Boskee\ProofHQ\SOAPWorkflowProofStageRequestObjectArray' => __DIR__ .'/SOAPWorkflowProofStageRequestObjectArray.php',
        'Boskee\ProofHQ\SOAPWorkflowProofRecipientObjectArray' => __DIR__ .'/SOAPWorkflowProofRecipientObjectArray.php',
        'Boskee\ProofHQ\SOAPWorkflowProofStageObject' => __DIR__ .'/SOAPWorkflowProofStageObject.php',
        'Boskee\ProofHQ\SOAPWorkflowProofStageObjectArray' => __DIR__ .'/SOAPWorkflowProofStageObjectArray.php',
        'Boskee\ProofHQ\SOAPWorkflowProofObject' => __DIR__ .'/SOAPWorkflowProofObject.php',
        'Boskee\ProofHQ\SOAPWorkflowProofObjectArray' => __DIR__ .'/SOAPWorkflowProofObjectArray.php',
        'Boskee\ProofHQ\SOAPWorkflowProofStageRequestUpdateObject' => __DIR__ .'/SOAPWorkflowProofStageRequestUpdateObject.php',
        'Boskee\ProofHQ\SOAPCustomFieldOptionObject' => __DIR__ .'/SOAPCustomFieldOptionObject.php',
        'Boskee\ProofHQ\SOAPCustomFieldOptionObjectArray' => __DIR__ .'/SOAPCustomFieldOptionObjectArray.php',
        'Boskee\ProofHQ\SOAPCustomFieldObject' => __DIR__ .'/SOAPCustomFieldObject.php',
        'Boskee\ProofHQ\SOAPCustomFieldObjectArray' => __DIR__ .'/SOAPCustomFieldObjectArray.php',
        'Boskee\ProofHQ\SOAPSectionObject' => __DIR__ .'/SOAPSectionObject.php',
        'Boskee\ProofHQ\SOAPSectionObjectArray' => __DIR__ .'/SOAPSectionObjectArray.php',
        'Boskee\ProofHQ\SOAPGroupMemberObject' => __DIR__ .'/SOAPGroupMemberObject.php',
        'Boskee\ProofHQ\SOAPGroupMemberObjectArray' => __DIR__ .'/SOAPGroupMemberObjectArray.php',
        'Boskee\ProofHQ\SOAPGroupObject' => __DIR__ .'/SOAPGroupObject.php',
        'Boskee\ProofHQ\SOAPGroupObjectArray' => __DIR__ .'/SOAPGroupObjectArray.php',
        'Boskee\ProofHQ\SOAPActivityLogObject' => __DIR__ .'/SOAPActivityLogObject.php',
        'Boskee\ProofHQ\SOAPActivityLogObjectArray' => __DIR__ .'/SOAPActivityLogObjectArray.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_72259f70a1bfb87ba4d832e1177092eb');

// Do nothing. The rest is just leftovers from the code generation.
{
}
